const SET_USERS = 'SET_USERS'
const SET_IS_USERS_LOADING = 'SET_IS_USERS_LOADING'
const SET_TOTAL_PAGES_COUNT = 'SET_TOTAL_PAGES_COUNT'
const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE'
const SET_TOTAL_USERS = 'SET_TOTAL_USERS'

export {
    SET_USERS,
    SET_IS_USERS_LOADING,
    SET_TOTAL_PAGES_COUNT,
    SET_CURRENT_PAGE,
    SET_TOTAL_USERS,
}